trigger:
  branches:
    include:
      - staging

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: templates/variables.yaml

stages:
  - stage: Deploy
    displayName: Deploy Trino
    jobs:
      - template: templates/deploy.yaml
