trigger:
  branches:
    include: [ "$(SOURCE_BRANCH)" ]

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: templates/variables.yaml

stages:
  - stage: CreateConfig
    displayName: Create/update K8s configuration resources
    jobs:
      - template: templates/create-config.yaml

  - stage: Deploy
    displayName: Deploy Trino
    jobs:
      - template: templates/deploy.yaml
