trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: templates/variables.yaml

stages:
  - stage: Delete
    displayName: Delete Trino
    jobs:
      - deployment: Delete
        displayName: Delete Trino Deployment
        environment: $(kubernetesEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: HelmDeploy@0
                  displayName: Helm uninstall Trino
                  inputs:
                    namespace: $(kubernetesNamespace)
                    command: uninstall
                    arguments: trino

                - task: Kubernetes@1
                  displayName: Delete resources in namespace
                  inputs:
                    command: delete
                    arguments: all --all
                    namespace: $(kubernetesNamespace)

                - task: Kubernetes@1
                  displayName: Delete PVCs in namespace
                  continueOnError: true
                  inputs:
                    command: delete
                    arguments: pvc --all
                    namespace: $(kubernetesNamespace)
