version: '3'

dotenv:
  - .env

env:
  COMMIT_SHA:
    sh: git rev-parse --short HEAD

vars:
  PROJECT_NAME: giga-dataops_trino

tasks:
  default:
    cmds:
      - task: up

  up:
    desc: Build and start Docker containers
    cmds:
      - docker compose --project-name giga-dataops-platform --file docker-compose-network.yaml up --detach --build --remove-orphans {{.CLI_ARGS}}
      - docker compose --project-name {{.PROJECT_NAME}} up --detach --build --remove-orphans {{.CLI_ARGS}}

  setup:
    desc: Run first-time setup tasks
    cmds:
      - pip install pre-commit
      - pre-commit install
      - helm repo add trino https://trinodb.github.io/charts/
      - helm repo update

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} stop {{.CLI_ARGS}}

  restart:
    desc: Restart containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} restart {{.CLI_ARGS}}

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} exec {{.CLI_ARGS}}

  clean:
    desc: Remove containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} down --volumes --remove-orphans {{.CLI_ARGS}}

  build-and-push:
    desc: Build and push Docker image
    cmds:
      - task: build
      - task: push

  build:
    internal: true
    desc: Build Docker image
    cmds:
      - docker build --tag {{.TRINO_IMAGE_REPOSITORY}}:{{.COMMIT_SHA}} .

  push:
    internal: true
    desc: Push Docker image
    cmds:
      - docker push {{.TRINO_IMAGE_REPOSITORY}}:{{.COMMIT_SHA}}

  k8s-prereqs:
    desc: Setup pre-requisite K8s resources
    dir: infra/k8s
    cmds:
      - kubectl apply -f namespace.yaml
      - kubectl apply -f secrets.yaml -n giga-trino
      - kubectl apply -f configmap.local.yaml -n giga-trino

  helm-up:
    desc: Install/upgrade Helm chart on a cluster running locally
    cmds:
      - task: k8s-prereqs
      - >
        helm upgrade --install trino ./infra/helm/trino
        --namespace giga-trino
        --set-string server.internalSharedSecret={{.SHARED_SECRET}}
        --set-file 'accessControl.rules.rules\.json'=./conf/rules.json
        --set-file additionalCatalogs.delta_lake=./conf/catalog/delta_lake.properties
        --set service.type=LoadBalancer

  helm-upi:
    desc: Install/upgrade Helm chart on a cluster with pre-configured HTTPS ingress
    cmds:
      - task: k8s-prereqs
      - >
        helm upgrade --install trino ./infra/helm/trino
        --namespace giga-trino
        --set-string server.internalSharedSecret={{.SHARED_SECRET}}
        --set-file additionalCatalogs.delta_lake=./conf/catalog/delta_lake.properties
        --set-file auth.groups=./conf/group.txt
        --set accessControl.refreshPeriod=5s
        --set auth.refreshPeriod=5s
        --set auth.passwordAuthSecret=giga-trino-secrets
        --set ingress.enabled=true
        --set ingress.annotations=null
        --set ingress.hosts[0].host={{.TRINO_INGRESS_HOST}}
        --set ingress.hosts[0].paths[0].path=/
        --set ingress.hosts[0].paths[0].pathType=Prefix
        --set envFrom[0].secretRef.name=giga-trino-secrets

  helm-down:
    desc: Uninstall Helm chart
    cmds:
      - helm uninstall trino --namespace giga-trino

  helm-clean:
    desc: Delete all K8s resources
    cmds:
      - kubectl delete all --all --namespace giga-trino
      - kubectl delete pvc --all --namespace giga-trino

  hash-password:
    desc: Generate hash for a password
    cmds:
      - echo '{{.CLI_ARGS}}' | htpasswd -inBC 10 {{.TRINO_ADMIN_USER}}

  trino:
    desc: Spawn an interactive Trino shell
    cmds:
      - task exec -- -it trino trino --user {{.TRINO_ADMIN_USER}}
