version: '3'

dotenv:
  - .env

vars:
  PROJECT_NAME: giga-dataops_trino

tasks:
  default:
    cmds:
      - task: up

  up:
    desc: Build and start Docker containers
    cmds:
      - docker compose --project-name giga-dataops-platform --file docker-compose-network.yaml up --detach --build --remove-orphans {{.CLI_ARGS}}
      - docker compose --project-name {{.PROJECT_NAME}} up --detach --build --remove-orphans {{.CLI_ARGS}}

  setup:
    desc: Run first-time setup tasks
    cmds:
      - pip install pre-commit
      - pre-commit install
      - helm repo add trino https://trinodb.github.io/charts/
      - helm repo update

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} stop {{.CLI_ARGS}}

  restart:
    desc: Restart containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} restart {{.CLI_ARGS}}

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} exec {{.CLI_ARGS}}

  clean:
    desc: Remove containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} down --volumes --remove-orphans {{.CLI_ARGS}}
      - docker compose --project-name giga-dataops-platform --file docker-compose-network.yaml down --volumes --remove-orphans {{.CLI_ARGS}}

  helm-up:
    desc: Install/upgrade Helm chart on a cluster running locally
    dir: infra
    cmds:
      - kubectl apply -f k8s/secrets.yaml
      - >
        helm upgrade --install trino ./helm/trino
        --namespace giga-trino
        --create-namespace
        --set-string server.internalSharedSecret={{.SHARED_SECRET}}
        --set service.type=LoadBalancer

  helm-upi:
    desc: Install/upgrade Helm chart with HTTPS-capable ingress
    dir: infra
    cmds:
      - kubectl apply -f k8s/secrets.yaml
      - >
        helm upgrade --install trino ./helm/trino
        --namespace giga-trino
        --create-namespace
        --set-string server.internalSharedSecret={{.SHARED_SECRET}}
        --set ingress.enabled=true
        --set ingress.annotations=
        --set ingress.hosts[0].host={{.TRINO_INGRESS_HOST}}
        --set ingress.hosts[0].paths[0].path=/
        --set ingress.hosts[0].paths[0].pathType=Prefix

  helm-down:
    desc: Uninstall Helm chart
    cmds:
      - helm uninstall trino --namespace giga-trino

  helm-clean:
    desc: Delete all K8s resources
    cmds:
      - kubectl delete all --all --namespace giga-trino
      - kubectl delete pvc --all --namespace giga-trino
