jobs:
  - deployment: Deploy
    displayName: Create/update K8s configuration resources
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Kubernetes@1
              displayName: Verify namespace secrets
              inputs:
                namespace: $(kubernetesNamespace)
                command: get
                arguments: secret oi-trino-secrets-$(deployEnv) -o yaml --ignore-not-found

            - task: Kubernetes@1
              displayName: Create secret
              inputs:
                namespace: $(kubernetesNamespace)
                configurationType: inline
                command: apply
                useConfigurationFile: true
                inline: |
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: "giga-trino-secrets-$(deployEnv)"
                    labels:
                      app.kubernetes.io/name: giga-trino
                      app.kubernetes.io/part-of: giga-dataops-platform
                      app.kubernetes.io/component: trino
                  stringData:
                    password.db: |-
                      $(adminAuth)
                      $(adminAuthGigaTrino)
                      $(adminAuthGigaSuperset)
                      $(adminAuthGigaDataIngestion)
                    group.db: |-
                      admin:giga-admin,tmadmin,admin
                      giga-trino:giga-trino
                      giga-superset:giga-superset
                      giga-ingestion-portal:giga-ingestion-portal
                    AZURE_STORAGE_ACCESS_KEY: "$(storageAccessKey)"
                    AZURE_STORAGE_ACCOUNT_NAME: "$(storageAccountName)"
                    HIVE_METASTORE_URI: "thrift://hive-metastore.ictd-ooi-dagster-$(deployEnv).svc.cluster.local:9083"
                    DEV_OIA_PRJRAZORDB_USER: "$(devPrjRazorDbUser)"
                    DEV_OIA_PRJRAZORDB_PASSWORD: "$(devPrjRazorDbPassword)"
                    DEV_OIA_PRJRAZORDB_CONNECTION_URL: "$(devPrjRazorDbConnectionUrl)"
                    GIGAMAPS_PRODUCTION_DB_CONNECTION_URL: "$(gigamapsProductionDbConnectionUrl)"
                    GIGAMAPS_PRODUCTION_USER: "$(gigamapsProductionUser)"
                    GIGAMAPS_PRODUCTION_PASSWORD: "$(gigamapsProductionPassword)"
                    GIGAMETER_PRODUCTION_DB_CONNECTION_URL: "$(gigameterProductionDbConnectionUrl)"
                    GIGAMETER_PRODUCTION_USER: "$(gigameterProductionUser)"
                    GIGAMETER_PRODUCTION_PASSWORD: "$(gigameterProductionPassword)"
