jobs:
  - deployment: Deploy
    displayName: Create/update K8s configuration resources
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Kubernetes@1
              displayName: Create config map
              inputs:
                namespace: $(kubernetesNamespace)
                configurationType: configuration
                command: apply
                useConfigurationFile: true
                configuration: $(Build.SourcesDirectory)/infra/k8s/configmap.yaml

            - task: Kubernetes@1
              displayName: Create secret
              inputs:
                namespace: $(kubernetesNamespace)
                configurationType: inline
                command: apply
                useConfigurationFile: true
                inline: |
                  apiVersion: v1
                  kind: Secret
                  metadata:
                    name: giga-trino-secrets
                    labels:
                      app.kubernetes.io/name: giga-trino
                      app.kubernetes.io/part-of: giga-dataops-platform
                      app.kubernetes.io/component: trino
                  stringData:
                    password.db: |-
                      $(adminAuth)
                      $(adminAuthGigaTrino)
                      $(adminAuthGigaSuperset)
                    group.db: |-
                      admin:giga-admin,tmadmin
                      giga-trino:giga-trino
                      giga-superset:giga-superset
                    AZURE_STORAGE_ACCESS_KEY: "$(storageAccessKey)"
                    AZURE_STORAGE_ACCOUNT_NAME: "$(storageAccountName)"

            - task: Kubernetes@1
              displayName: Create ExternalName service for Hive Metastore
              inputs:
                namespace: $(kubernetesNamespace)
                configurationType: inline
                command: apply
                useConfigurationFile: true
                inline: |
                  apiVersion: v1
                  kind: Service
                  metadata:
                    name: hive-metastore-external
                    labels:
                      app.kubernetes.io/name: giga-trino
                      app.kubernetes.io/part-of: giga-dataops-platform
                      app.kubernetes.io/component: trino
                  spec:
                    type: ExternalName
                    externalName: "hive-metastore.ictd-ooi-dagster-$(deployEnv).svc.cluster.local"
                    ports:
                      - port: 9083
                        protocol: TCP
                        targetPort: 9083
