jobs:
  - deployment: Deploy
    displayName: Trino Deployment
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Helm deploy Trino
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/trino"
                releaseName: trino
                namespace: $(kubernetesNamespace)
                arguments: >
                  --set-string server.internalSharedSecret="$(sharedSecret)"
                  --set ingress.enabled=true
                  --set image.repository="$(containerRegistryName).azurecr.io/giga-trino"
                  --set-string image.tag="$(Build.SourceVersion)"
