jobs:
  - deployment: Deploy
    displayName: Trino Deployment
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Helm deploy Trino
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/trino"
                releaseName: trino
                namespace: $(kubernetesNamespace)
                arguments: >
                  --set-string server.internalSharedSecret="$(sharedSecret)"
                  --set-file 'accessControl.rules.rules\.json'="$(Build.SourcesDirectory)/conf/rules.json"
                  --set-file additionalCatalogs.delta_lake="$(Build.SourcesDirectory)/conf/catalog/delta_lake.properties"
                  --set ingress.enabled=true
                  --set ingress.hosts[0].host="io-trino-$(deployEnv).unitst.org"
                  --set ingress.hosts[0].paths[0].path=/
                  --set ingress.hosts[0].paths[0].pathType=Prefix
                  --set envFrom[0].secretRef.name="giga-trino-secrets-$(deployEnv)"

            - task: Kubernetes@1
              displayName: Restart deployments
              condition: eq(variables['Build.Reason'], 'Manual')
              inputs:
                namespace: $(kubernetesNamespace)
                command: rollout
                arguments: restart deployment
