jobs:
  - deployment: Deploy
    displayName: Trino Deployment
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Helm deploy Trino
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/trino"
                releaseName: trino
                namespace: $(kubernetesNamespace)
                arguments: >
                  --set-string server.internalSharedSecret="$(sharedSecret)"
                  --set-file 'accessControl.rules.rules\.json'="$(Build.SourcesDirectory)/conf/rules.json"
                  --set-file additionalCatalogs.delta_lake="$(Build.SourcesDirectory)/conf/catalog/delta_lake.properties"
                  --set ingress.enabled=true
