stages:
  - stage: CreateConfig
    displayName: Create/update K8s configuration resources
    jobs:
      - template: create-config.yaml

  - stage: Uninstall
    displayName: Uninstall Trino
    jobs:
      - template: helm-uninstall.yaml

  - stage: Deploy
    displayName: Deploy Trino
    jobs:
      - template: helm-deploy.yaml
