jobs:
  - deployment: Deploy
    displayName: Trino Deployment
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Helm deploy Trino
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/trino"
                releaseName: trino
                namespace: $(kubernetesNamespace)
                force: true
                arguments: >
                  --set-string server.internalSharedSecret="$(sharedSecret)"
                  --set-file additionalCatalogs.delta_lake="$(Build.SourcesDirectory)/conf/catalog/delta_lake.properties"
                  --set-file auth.groups="$(Build.SourcesDirectory)/conf/group.txt"
                  --set ingress.enabled=true
                  --set ingress.hosts[0].host="io-trino-$(deployEnv).unitst.org"
                  --set ingress.hosts[0].paths[0].path=/
                  --set ingress.hosts[0].paths[0].pathType=Prefix
                  --set envFrom[0].secretRef.name="giga-trino-secrets-$(deployEnv)"
                  --set auth.passwordAuthSecret="giga-trino-secrets-$(deployEnv)"
